### ISSUE TITLE
Game state (saves, progress, etc) gets wiped after shutting down Lutris

### ISSUE THREAD

**Issue by PureTryOut** [flathub/net.lutris.Lutris#134]
**Describe the problem**
I recently bought Surviving Mars from GOG and used Lutris to install it (it's a native Linux game). It works and runs perfectly, but the save games get wiped after I quit Lutris. It also forgets that I already completed the tutorial, and basically seems like it thinks I start the game for the first time again.

**Is it reproducible with native Lutris?**
No clue, I can't run it due to my system being non-multilib and based on Musl (Alpine Linux), but I doubt it.

**Steps to reproduce**
1. Install Surviving Mars from GOG
2. Start a game and save it
3. Quit the game and Lutris
4. Restart Lutris and the game

**Expected behavior**
The game saves to remain

**Actual behavior**
The games saves are gone

**Flatpak info**
`flatpak --version`: 1.8.3

**Comment by PureTryOut** [comment]
I actually fixed this by allowing the Flatpak access to `$HOME`. Not ideal...
It created `$HOME/.local/share/Surviving Mars` where it stores everything.

**Comment by A6GibKm** [comment]
Could you check if that is also being created at `~/.var/app/net.lutris.Lutris/data`? which is a local equivalent of `share`.

Note that lutris only knows `~/Games` and xdg-dirs like Downloads or Music.

**Comment by PureTryOut** [comment]
```
> ls ~/.var/app/net.lutris.Lutris/data/
icons/  lutris/  recently-used.xbel  webkitgtk/
```

So no, nothing from the game is created there.

**Comment by A6GibKm** [comment]
Is this a problem only with this game? The idea is that if a games saves data to XDG_DATA_HOME (which defaults to ~/.local/share) it will be stored in ~/.var/... instead.

My intuition is that the game instead of using XDG_DATA_HOME, it saves to a hardcoded path (~/.local/share/...) and since it does not have access to it you loose the data.

My recommendation would be to remove the HOME access you just added and add a permissions to `~/.local/share/Surviving Mars`.

**Comment by strycore** [comment]
It's not possible to contact the developer of many legacy games because many studios no longer exist. This is especially true for Linux games which often get an initial port but never receive updates.

The most obvious solution is to give access to home. If or when Lutris can ask for permissions for a folder dynamically in Flatpak then we could have that instead. We're going to start tracking game saves locations for a cloud save feature. But this has the potential of becoming a mess. With a setup like mine where I have the entirety of my Humble Bundle library installed, this would result in hundreds of permissions added to Flatpak.

**Comment by Zenek963** [comment]
Better idea is add `--persist=.` this should help with native games even it save game data directly in home folder

**Comment by A6GibKm** [comment]
`home` access was already added. This should be fixed. Please open the issue if it persists.

I think it is not possible to run Lutris decently without `home` access.
