### ISSUE TITLE
What's the end goal here?

### ISSUE THREAD

**Issue by nickavem** [flathub/net.lutris.Lutris#151]
I'm a little confused as to what the big picture goals of this flatpak are:

1. Will it ever not be in "Beta"?
2. How do we decide when it's not in Beta?
3. What does the flatpak want to support, what does it not want to support?
4. Why support apps that are already supported elsewhere on Flathub?

I also think something like a CONTRIBUTING.md would be great because I'd love to help out here, it's just a bit structurally confusing right now.

**Comment by Saroufim** [comment]
As someone who followed the project from the start but is not a direct contributor, I can say that the goal is to have someone contribute all the necessary patches upstream to unblock all the remaining disparities between the flatpak version and the one that is regularly distributed. It is not easy to make such a complex software work seamlessly inside a sandboxed environment and  I don't think that any of the maintainers have the time needed to do that because they are also handling other projects. You can see @gasinvein, for example, being busy in other important projects on flathub and other packaging sites.  @RobLoach probably has his hands full with RetroArch. And so on and so forth. If someone steps in and contributes the code, it will be released.

**Comment by RobLoach** [comment]
>     1. Will it ever not be in "Beta"?

I would love for it to be, but personally I'm not that confident on it since Lutris itself isn't even considered stable yet.

>     2. How do we decide when it's not in Beta?

When we're confident on its installation and usage. Lutris itself can be very confusing to the average user, so I'd be cautious on just assuming the flatpak release is stable. Lutris itself is still not even tagged *1.0.0* stable, for example.

>     3. What does the flatpak want to support, what does it not want to support?

Since Lutris aims to add support to a whole sort of applications, it can be difficult to know what we want to ensure is available in the flatpak release. Being able to download a native game like SuperTuxKart and playing it seems like a good base-line.

>     4. Why support apps that are already supported elsewhere on Flathub?

I'm not sure what you mean by this. Lutris aims to give you a User Interface to download and play many games. Whether or not they're available on Flathub is irrelevant. In fact, there's even an issue about adding a Flatpak runner within Lutris itself: https://github.com/lutris/lutris/issues/3509

> I also think something like a CONTRIBUTING.md would be great because I'd love to help out here, it's just a bit structurally confusing right now.

Most definitely. There's the [runner issue](https://github.com/flathub/net.lutris.Lutris/blob/beta/.github/ISSUE_TEMPLATE/runner-issue.md) template, but would love to see more documentation.

**Comment by A6GibKm** [comment]
> Will it ever not be in "Beta"?

To many runners are not working, this is inherently hard due to the runner model. On the other hand the Lutris developers are not interested right now in providing support for this Flatpak. 

> How do we decide when it's not in Beta?

Let me start saying that the most problematic issue with this Flatpak arises precisely from it being a beta (#53) which is a reason to aspire stable status. I don't know what it will take, this is an inherently hard app to sandbox, there isn't a clear way of determining if the app works well enough for stable status and we certainly don't want users to have a bad time trying to run runners that are impossible to run.

> What does the Flatpak want to support, what does it not want to support?

It would be my hope to support mostly everything, but it is too much of a job for me. I don't have the knowledge nor the time to support everything. Being more concrete, the priority should be supporting the commonly used runners.

**Comment by alvarlagerlof** [comment]
> To many runners are not working. 

Currenly, wine seems to be doing all I exepect it to do flawlessly. I'd aruge that wine is what the vast majority of people use this for. With the steam deck launching soon, and the primary method of installing apps on it being flatpaks, it would be good I think, it move this out of beta, maybe with a warning at lanch about what does not work in flatpak currently. Many other flatpaks do this. 

I think doing that would go a very long way towards a better user experience for most people especailly considering the current installation method and the amount of people not realising they need to manually add runtimes too.

**Comment by gasinvein** [comment]
I'd consider this as the main issue here:

> Lutris developers are not interested right now in providing support for this Flatpak.

Leaving beta also means more of less savvy users; providing good experience for them isn't sustainable without upstream involvement.

**Comment by A6GibKm** [comment]
> I'd consider this as the main issue here:
> 
> > Lutris developers are not interested right now in providing support for this Flatpak.
> 
> Leaving beta also means more of less savvy users; providing good experience for them isn't sustainable without upstream involvement.

As things are, I would prefer to stay as beta until, either

  - We get involvement from upstream
  - Someone helps me improving the Flatpak, as I don't have the time required for such endeavor 
  
Right now, we cannot even upgrade to the latest version.

**Comment by alvarlagerlof** [comment]
> Right now, we cannot even upgrade to the latest version.

What is the reason for this?

**Comment by A6GibKm** [comment]
> > Right now, we cannot even upgrade to the latest version.
> 
> What is the reason for this?

Lutris can't open games, and shows an unrelated error. See https://github.com/flathub/net.lutris.Lutris/pull/159. It says a certain file cannot be found in `/tmp` but given that flatpak does have write access to its  tmp the error has to be elsewhere.

**Comment by strycore** [comment]
The client is barely functional and almost every runner is broken. There is a substantial amount of work for this to leave beta.

**Comment by A6GibKm** [comment]
Current status: on track to leave beta

Idk how long this will take though

**Comment by Mershl** [comment]
There has been great progress and involvement from upstream in the last few months. What are your thoughts on moving to stable @A6GibKm?

**Comment by A6GibKm** [comment]
It can move to stable whenever @strycore  thinks it works well enough to expose it to a bigger audience and deems it stable enough.

**Comment by strycore** [comment]
The next release (0.5.11) can be pushed directly to Flathub stable.

**Comment by strycore** [comment]
Lutris 0.5.11 beta is out, we can push this release to Flathub beta then push the final release to Flathub

https://github.com/lutris/lutris/releases/tag/v0.5.11-beta1

**Comment by strycore** [comment]
Lutris 0.5.11 is out, how do we proceed to remove lutris from flathub beta and push it to stable?

**Comment by bilelmoussaoui** [comment]
@strycore I have created a master branch, pushing any changes to it would trigger a build that would publish to stable. We don't have an easy way to remove things from the beta branches so far, I would recommend opening an issue on https://github.com/flathub/flathub so that someone with proper access can handle it.

**Comment by strycore** [comment]
@bilelmoussaoui thanks a lot! I'll push the update to the master branch right away.

**Comment by TheEvilSkeleton** [comment]
It's live!! https://flathub.org/apps/details/net.lutris.Lutris

**Comment by strycore** [comment]
Closing this issue
